- src/scworkflow/rename_clustering.py
- tests/test_rename_clustering.py
- tests/test_rename_clustering_basic.py
Please double check the added new function "rename_clustering" as well as its test file.
> add function rename_clustering

- src/scworkflow/rename_clustering.py
- src/scworkflow/threshold_heatmap_module.py
- tests/test_rename_clustering.py
- tests/test_threshold_heatmap.py
Please check the function of threshold-heatamp as well as the test file for this function.
> Threshold heatmap

- src/scworkflow/threshold_heatmap_module.py
- tests/test_threshold_heatmap.py
Changed the output from the threshold heatmap to the dictionary
> Update threshhold heatmap

- tests/test_data_utils/test_combine_dfs.py
- tests/test_data_utils/test_load_csv_file.py
- tests/test_transformations/test_analysis.py
- tests/test_transformations/test_rename_clustering.py
- tests/test_transformations/test_rename_clustering_basic.py
- tests/test_visualization/test_hierarchical_heatmap.py
- tests/test_visualization/test_threshold_heatmap.py
Move tests to corresponding folders.
> style(package): Update test directory

- src/spac/data_utils.py
- tests/test_data_utils/test_downsample_cells.py
- tests/test_data_utils/test_select_values.py
This pull request includes two functions: select_values and downsample_cells, which append to data_utils.py,
as well as the corresponding tests named as "test_select_values.py" and "test_downsample_cells.py" for your review. 
Please let me know if any changes or updates are required.
> select_values and downsample_cells

- src/spac/data_utils.py
- tests/test_data_utils/test_downsample_cells.py
- tests/test_data_utils/test_select_values.py
I have modified two functions, "select_values" and "downsample_cells" as well as corresponding testing files for your review.
Please let me know if any issues related to this quest. Thank you.
> feat: select_values_downsample and tests

- src/spac/data_utils.py
- src/spac/transformations.py
- src/spac/visualization.py
- tests/test_data_utils/test_downsample_cells.py
- tests/test_transformations/test_rename_observations.py
- tests/test_visualization/test_threshold_heatmap.py
Change wording from intensity to features to be consistent with the descriptions.
> Updating variable naming and some linting

- .github/workflows/gitflow-py-action.yml
New CI is implemented specifically for python package development in the gitflow-py repository.
> Update CI file

- src/spac/data_utils.py
- tests/test_data_utils/test_calculate_centroid.py
Added calculate_centroid function and corresponding unit tests,
> feat(calculate_centroid): New feature and unittest

- src/spac/visualization.py
- tests/test_visualization/test_threshold_heatmap.py
I have refactored the function "threshold_heatmap" of visualization.py as well as corresponding "test_threshold_heatmap" for your review. Please let me know if any issues related to this function.
> refactor: modify colormap and tests

- src/spac/data_utils.py
- src/spac/utils.py
- tests/test_data_utils/test_bin2cat.py
- tests/test_data_utils/test_ingest_cells.py
- tests/test_transformations/test_batch_normalize.py
- tests/test_transformations/test_subtract_min_per_region.py
- tests/test_utils/__init__.py
- tests/test_utils/test_regex_search_list.py
Added new regex_search_list in utils.py to achieve more rigorous regex search. 
Updated the ingest_data and bin2cat function to use the regex_search_list function.
Updated unittests to use more rigorous regex search, only so can pass the previous unit tests.
> Added new helper function regex_search_list

- src/spac/visualization.py
- tests/test_visualization/test_histogram.py
@georgezakinih  This new pull request is the exact one that you have reviewed this morning without any changes.
I have to close the previous one and create this new one merely for resolving merge conflicts at the early time.
Hopefully this won't make you confused too much and it is ready to go to merge :) Thanks again.
> refactor: final update for histogram and unit tests

- src/spac/visualization.py
- tests/test_visualization/test_spatial_plot.py
Spatial plot for visualizing feature and observations
> feat(spatial_plot): Function and tests

- .github/workflows/gitflow-py-action.yml
> Update passing token

- src/spac/visualization.py
- tests/test_visualization/test_histogram.py
Hi Rui, please review the refactored function "histogram" and corresponding unit tests. Thank you!
> refactor: histogram and unittests

- src/spac/transformations.py
- tests/test_transformations/test_rename_observations.py
I have refactored the function of rename_observations and unit tests for your review. Thanks!
> refactor: rename and Unittests

- src/spac/visualization.py
- tests/test_visualization/test_tsne_plot.py
I have refactored tsne_plot and corresponding unit tests for your review. Thanks
> refactor: tsne_plot and Unit tests

- src/spac/transformations.py
- tests/test_transformations/test_umap.py
Please review the code for function "UMAP" and the unit test at your convenience. Thanks.
> create: umap 

- src/spac/visualization.py
- tests/test_visualization/test_dimensionality_reduction_plot.py
Please review the new function named as dimensionality_reduction_plot at your convenience. Thanks!
> create: dimensionality_reduction_plot

- src/spac/visualization.py
- tests/test_visualization/test_boxplot.py
update new feature boxplot and test
> feat: create boxplot and test

- src/spac/transformations.py
- tests/test_transformations/test_get_cluster_info.py
Please review the modified get_cluster_info function at your convenience. Thanks!
> create: modified get_cluster_info and test

- src/spac/visualization.py
- tests/test_visualization/test_dimensionality_reduction_plot.py
@georgezakinih I made new updates for dimensionality_reduction_plot function and corresponding unittest by checking the existence of adata.obsm['X_umap'] and adata.obsm['X_tsne']. Thank you for any comments and suggestions.
> create: 3rd edition of dimensionality_reduction_plot and test

- src/spac/transformations.py
- tests/test_transformations/test_phenograph_clustering.py
Please review the refactored phenograph_clustering function at your convenience. Thanks!
> refactor: phenograph_clustering and test

- src/spac/data_utils.py
- tests/test_data_utils/test_ingest_cells.py
> Ingest cells v03

- src/spac/visualization.py
- tests/test_visualization/test_histogram.py
Please review the refactored histogram function at your convenience. Thanks!
> refactor: histogram_v0.3 and unit tests

- src/spac/data_utils.py
- tests/test_data_utils/test_combine_dfs.py
- tests/test_data_utils/test_combine_dfs_depracated.py
Hi @georgezakinih, this is the combine_dfs update to replace the previous function. Thanks.
> feat: Update test & func for combine_dfs

- src/spac/data_utils.py
- tests/test_data_utils/test_append_annotation.py
- tests/test_data_utils/test_append_observation.py
Hi @georgezakinih , this is the updated version to address previous comments. Thanks.
> Updated Append Annotation

- src/spac/visualization.py
- tests/test_visualization/test_hierarchical_heatmap.py
Hi @georgezakinih Here is the refactored hierarchical_heatmap function for your review. 
Also this function has been tested with real dataset by visualization.
Please find extra explanation of parameters on JIRA ticket:
https://tracker.nci.nih.gov/browse/DSP-190
> refactor: hierearchical_heatmap and unittest_v0.3

- src/spac/data_utils.py
- tests/test_data_utils/test_downsample_cells.py
Please review the refactored downsample_cells function at your convenience. Thanks!
Please find the relevant JIRA ticket and updated explanation of stratification at
https://tracker.nci.nih.gov/browse/DSP-186
> Downsample v0.3

- setup.py
- src/spac/spatial_analysis.py
- src/spac/utils.py
- tests/test_spatial_analysis/test_spatial_interaction.py
- tests/test_utils/test_check_annotation.py
Hi @georgezakinih, please find the updates to the function that exposes the n_neighs, radius and coordinate type for squidpy spatial neighbor function with tests. Thanks.
> Updated Spatial Plot with n_neighs, radius, and coortype with tests

- src/spac/transformations.py
- tests/test_transformations/test_arcsinh_transformation.py
@georgezakinih Please review the arcsinh_transformation function at your convenience. Thanks!
> feat: arcsinh_transformation and unit tests

- src/spac/transformations.py
@georgezakinih As we discussed before, I added the **kwargs in the phenograph_clustering function for your review or merge. Thank you!
> refactor: revised phenograph_clustering function

- src/spac/transformations.py
@georgezakinih as we discussed, I have removed "layer" in the rename_annotations function for your review.
> refactor: rename_annotations function

- src/spac/transformations.py
- tests/test_transformations/test_run_umap.py
Hi @georgezakinih The refactored run_umap function is ready for your review at your convenience. Thank you!
Note: I replaced the previous function name "umap" with "run_umap" to avoid the conflict with umap library name.
> refactor: run_umap and unit tests

- src/spac/visualization.py
- tests/test_visualization/test_interactive_spatial_plot.py
Hi @georgezakinih , please find the updated interactive spatial plot. Thanks!
> Updated Interactive Spatial Plot 

- .github/workflows/gitflow-py-action.yml
Change production and development artifact rid
> doc: Update github action file

- CHANGELOG.md
- setup.py
- src/spac/__init__.py
- src/spac/visualization.py
> Release dev to main

- src/spac/transformations.py
- tests/test_transformations/test_batch_normalize.py
Hi @georgezakinih could you please review the fixed batch_norm and its unit test at your convenience? Thank you.
> fix: batch_norm and unit test

- src/spac/transformations.py
- tests/test_transformations/test_batch_normalize.py
This pull request is from dev to release_dev for batch_normalize function.
> Dev to release_dev: batch_normalize

- src/spac/data_utils.py
- src/spac/transformations.py
- tests/test_data_utils/test_adata_select_values.py
- tests/test_data_utils/test_dataframe_select_values.py
- tests/test_data_utils/test_select_values.py
- tests/test_transformations/test_get_cluster_info.py
to merge select_values and get_cluster_info from dev to release_dev
> merge select_values and get_cluster_info to release_dev

- tests/test_visualization/test_visualize_2D_scatter.py
add comment to merge release_dev
> fix(test_ visualize_2D): add comment to merge release_dev

- src/spac/utils.py
- src/spac/visualization.py
- tests/test_utils/test_annotation_category_relations.py
Updated the annotation relation extraction to include percentage of target in source, and source in target.
> Update Sankey plot and its utils

- src/spac/utils.py
- src/spac/visualization.py
- tests/test_utils/test_annotation_category_relations.py
- tests/test_visualization/test_sankey_plot.py
Hi @georgezakinih , this is the Sankey plot with the description updated.
Thank you.
> Sankey plot updates

- src/spac/data_utils.py
This pr is addressing the comments on Jira ticket https://tracker.nci.nih.gov/browse/DSP-346
key points include:
1. add the summary of the returned dataset, especially the count of cells that matches the selected labels
2. use the python logging package, no need for unit test for it.
3.  print a description of the default layer of the output anndata object
> fix(select_values): add summary in function using logging

- src/spac/transformations.py
- tests/test_transformations/test_batch_normalize.py
These two features were added to the batch_normalize function:
1. Added the option for z_score, and add a unit test as well.
2. Added a new argument for input_layer, and corresponding unit test.
Also, added a check that the input argument "log" is boolean.
> feat(batch_normalize): add features input_layer and z-score method and fix unit tests

- src/spac/visualization.py
- tests/test_visualization/test_histogram.py
minor changes on comments and pull request from histogram to dev
> fix: histogram and unit test on commits

- src/spac/visualization.py
- tests/test_visualization/test_histogram.py
update histogram with minor changes on comments from dev to release_dev
> merge histogram from dev to release_dev

- src/spac/data_utils.py
@ruiheesi , make a minor change regarding the name of the csv files being merged.
> refactor(logging): Update log messages in function load_csv

- CHANGELOG.md
- setup.py
- src/spac/__init__.py
- src/spac/spatial_analysis.py
- tests/test_spatial_analysis/test_neighborhood_profile.py
- tests/test_spatial_analysis/test_neighborhood_profile_core.py
Hi Fang, this is the core functionality for spatial umap
> Neighborhood profile

- src/spac/data_utils.py
- src/spac/spatial_analysis.py
- src/spac/transformations.py
- src/spac/utils.py
- tests/test_spatial_analysis/test_neighborhood_profile.py
- tests/test_spatial_analysis/test_neighborhood_profile_core.py
- tests/test_transformations/test_arcsinh_transformation.py
- tests/test_transformations/test_batch_normalize.py
- tests/test_transformations/test_phenograph_clustering.py
- tests/test_transformations/test_run_umap.py
- tests/test_transformations/test_select_input_features.py
- tests/test_transformations/test_validate_transformation_inputs.py
- tests/test_utils/test_check_list_in_list.py
- tests/test_utils/test_check_table.py
fix(batch_normalize): minor changes on comments of function and unit test
> merge fix(batch_normalize) from dev to release_dev

- src/spac/utils.py
- src/spac/visualization.py
- tests/test_utils/test_annotation_category_relations.py
- tests/test_visualization/test_relational_heatmap.py
Hi @georgezakinih, I've created the relational_heatmap function with unittests, and updated the relationship calculation to address the same column input scenario. Please let me know if this works. Thanks.
> Initial addition of relational heatmap

- src/spac/transformations.py
- tests/test_transformations/test_apply_per_batch.py
- tests/test_transformations/test_arcsinh_transformation.py
- tests/test_transformations/test_arcsinh_transformation_core.py
- tests/test_transformations/test_normalize_features.py
- tests/test_transformations/test_normalize_features_core.py
Hi @ruiheesi Please review this PR for a new feature of intra_batch normalization at your convenience.
The design architecture includes three layers of functions:
Core functions: Focus on computations.
Intermediate function: Handles batch processing.
Landing functions: Manage anndata-specific operations.
For more details, please refer to the JIRA ticket DSP-381 (https://tracker.nci.nih.gov/browse/DSP-381)
As suggested by George, we have maintained this architecture. Please review the code and let me know if you have any questions or would like to have a brief meeting. Thank you.
> feat(normalize_per_batch): add intra_batch normalization and unit tests

- src/spac/transformations.py
- src/spac/utils.py
- src/spac/visualization.py
- tests/test_transformations/test_apply_per_batch.py
- tests/test_transformations/test_arcsinh_transformation.py
- tests/test_transformations/test_arcsinh_transformation_core.py
- tests/test_transformations/test_normalize_features.py
- tests/test_transformations/test_normalize_features_core.py
- tests/test_utils/test_annotation_category_relations.py
- tests/test_visualization/test_relational_heatmap.py
This is to start the relational heatmap template dev after the load csv.
> PR for relational heatmap

- src/spac/spatial_analysis.py
- src/spac/transformations.py
- src/spac/visualization.py
- tests/test_transformations/test_phenograph_clustering.py
- tests/test_transformations/test_run_umap.py
- tests/test_transformations/test_select_input_features.py
- tests/test_transformations/test_validate_transformation_inputs.py
- tests/test_visualization/test_dimensionality_reduction_plot.py
update the functions (phenograph_clustering, neighborhood_profile, run_umap, visualize_2D_scatter) related to add associate_table.
> merge dev to release_dev

- src/spac/visualization.py
- tests/test_visualization/test_boxplot.py
In this update, correct single feature orientation and add x/ y-axis label in the function code, and corresponding unit tests.
> merge the boxplot from dev to release dev

- src/spac/visualization.py
This is the demonstration of the CD process, no significant change is here.
> perf: deming CD

- tests/test_transformations/test_phenograph_clustering.py
This PR is for a unittest for phenograph clustering with feature subsetting
> Added feature subsetting unit tests for raw data

- src/spac/spatial_analysis.py
- tests/test_spatial_analysis/test_spatial_interaction.py
HI George, this is the update for moving some functions from NDIAP to local, including:
1. Set default color map for heatmap to seismic for better visual representation
2. Add the pandas dataframe with proper column name and row index into the return:
a). Add function to extract the labels from the figure object
b). Add function to process the matrix to assign proper row index and column name
c). Return the proper file name to support image data export as well.
3. Update the docstring of the function
Thanks. The JIRA ticket link: https://tracker.nci.nih.gov/browse/DSP-455
> T2 spatial interaction

- src/spac/spatial_analysis.py
- tests/test_spatial_analysis/test_calculate_nearest_neighbor.py
the new name nearest_neighbor is more specific than spatial_distance
> fix: replace name spatial_distance with nearest_neighbor

- src/spac/visualization.py
- tests/test_visualization/test_relational_heatmap.py
Jira ticket:
https://tracker.nci.nih.gov/browse/DSP-462
> T2 2024 update: include dataframe return

- src/spac/utils.py
- src/spac/visualization.py
- tests/test_visualization/test_interactive_spatial_plot.py
HI @georgezakinih, this is the T2 update for interactive spatial plot.
This round of update incorporates the NIDAP template updates into the current package code including:
1. The group name display as a label and labels under the group for stratify options
2. The file name creation and sanitizing for nidap filesystem compliant
3. The stratify option
4. Change the return to list of dictionaries
> T2 interactive spatial plot

- setup.py
This commit is to trigger the minor version increase through the step flag in commit message.
> step: version 0.8.0 release

- environment.yml
- src/spac/transformations.py
- src/spac/utag_functions.py
- tests/test_transformations/test_utag_clustering.py
feat(core): add UTAG clustering method and tests for it.
> Add utag clustering

- src/spac/transformations.py
- tests/test_transformations/test_add_qc_metrics.py
Add function for computing common quality control metrics for single cell spatial/transcriptomics analysis.
> feat(qc-metrics): add common single cell quality control metrics

- src/spac/transformations.py
- src/spac/utils.py
- tests/test_transformations/test_get_qc_summary_table.py
- tests/test_utils/test_compute_summary_qc_stats.py
Add high level get_qc_summary_table function for computing summary statistic for sc quality control data to transformations.py.
Add unit tests for get_qc_summary_table function.
Add lower level compute_summary_qc_stats function to utils.py.
> feat(qc_summary_statistics): add summary statistics table for sc/spatial transcriptomics quality control metrics

- src/spac/templates/template_utils.py
- tests/templates/test_template_utils.py
this is reopening the previous PR with fixes
> Refactor: template-utils with review fixes 
