.gitignore, tests/test_threshold_heatmap.py
The origin method uses the magic mock, which does not have the anndata.obs_name field, leading to failure of unitest.
=> Hotfix test threshold heatmap

src/spac/transformations.py, tests/test_transformations/test_rename_observations.py
This pull request includes the refactored rename_observations function and the corresponding tests for your review. 
Notes for the results of "Use flake8 to check code":
1. "test_rename_observations.py:10:1: E402 module level import not at top of file"
sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../src")
from spac.transformations import rename_observations
* import line should follow sys.path.append().
2. "transformations.py:1:1: F401 're' imported but unused
transformations.py:2:1: F401 'seaborn' imported but unused
transformations.py:6:1: F401 'anndata as ad' imported but unused
transformations.py:8:1: F401 'matplotlib.pyplot as plt' imported but unused
transformations.py:9:1: F401 'sklearn.preprocessing.MinMaxScaler' imported but unused"
* I will modify these lines …
=> feat: final rename_observations and tests

src/spac/utils.py, tests/test_utils/test_anndata_checks.py
The function has two sets of checks:
Internal (dev) facing: check for input types
External (user) facing: check if input exists in the anndata object.
=> Add error handling utils for anndata checks

src/spac/visualization.py, tests/test_visualization/test_threshold_heatmap.py
Please review the refactored threshold_heatmap function at your convenience. Thanks!
Here is the updated requirements of refactoring this function for your reference.
https://tracker.nci.nih.gov/browse/DSP-198
Briefly, in the refactored function:
1.	Add the layer option.
2.	Handle **kwargs and add an option to switch the axis. If swap_axes is part of kwargs from scanpy, we will not add it separately but show in the unit tests how to use it.
3.	Use utility functions from utility.py to check input arguments.
The refactored unit tests now include:
•	A test for the swap_axes parameter passed via **kwargs.
•	Removal of direct input validation tests since we are using utility functions to handle input validation.
=> refactor: threshold_heatmap_v0.3 and tests

src/spac/utils.py, tests/test_utils/test_regex_search_list.py
This update is to hotfix error discovered by Scott to provide better error handling when regex pattern has syntax error.
=> hotfix for regex pattern error

src/spac/data_utils.py, tests/test_data_utils/test_adata_select_values.py, tests/test_data_utils/test_dataframe_select_values.py, tests/test_data_utils/test_select_values.py
This refactoring splits the original functionality of select_values into three distinct functions:
select_values(data, annotation, values=None) is the landing function. 
data can be either dataframe or anndata. 
Based on the data type, it delegates the operation to one of the two specialized functions: 
dataframe_select_values for a DataFrame or adata_select_values for an AnnData object.
Accordingly, three unit tests were added.
=> fix(select_values): expanded the original function and added corresponding unit tests

src/spac/visualization.py, tests/test_visualization/test_histogram.py
1. modified test_histogram_feature_group_by_one_label_annotation
2. If no feature or annotation is specified, apply default to the first feature in adata.var_names
3. add a unit test to verify the behavior when no feature or annotation is provided, ensuring that the first feature is selected by default and a warning is raised.
=> fix:histogram and corresponding unit tests

src/spac/transformations.py, tests/test_transformations/test_batch_normalize.py
Including .copy() ensures that the original data remains intact while performing normalization.
=> refactor: batch_normalize and unit test

src/spac/transformations.py, tests/test_transformations/test_arcsinh_transformation.py
addressed the issue of handling a non-existing annotation and providing a more informative error message;
Added a specific ValueError when both co_factor and percentile are None with a detailed error message.
=> fix(arcsinh_transformation): add error message and unit tests

src/spac/transformations.py, tests/test_transformations/test_arcsinh_transformation.py
Hi @georgezakinih this commit has used the "Check annotation" utility function, and printed received "negative value" in the error message. Thank you for reviewing.
=> fix(arcsinh_transformation): change error message and unit tests

src/spac/data_utils.py
Problem: Adding columns one at a time to a large DataFrame causes fragmentation and performance issues. The warning suggests using pd.concat(axis=1) to add all new columns at once. 
Solution: Calculate new columns separately.  Use pd.concat(axis=1) to concatenate new columns to the original DataFrame in one operation, avoiding fragmentation.
=> fix(calculate_centroid): add new columns in a single operation

src/spac/spatial_analysis.py, tests/test_spatial_analysis/test_calculate_spatial_distance.py
Hi @georgezakinih from our latest discussion, I have refactored the calculate_spatial_distance function again by storing the output in adata.obsm instead of adata.un, and removing the subset parameter.
here is the commit for your review at your convenience.
[https://github.com/FNLCR-](https://github.com/FNLCR-DMAP/SCSAWorkflow/commit/f2c38aa8605c3fac36c4428a609df6e0d8c1e821)
=> fix: store the output in adata.obsm and remove subset

src/spac/spatial_analysis.py, tests/test_spatial_analysis/test_calculate_nearest_neighbor.py
The refactored version of calculate_nearest_neighbor resolved the index mismatch by reindexing the result DataFrame before storing it in adata.obsm. This ensures the final DataFrame will have exactly the same row labels (and order) as adata.obs_names, which Anndata requires for storing in .obsm.
=> fix(calculate_nearest_neighbor): reindex to match adata.obs and unit test

src/spac/data_utils.py, tests/test_data_utils/test_select_values.py
In AnnData, slicing operations like filtered_data = data[data.obs[annotation].isin(values)] will by default create a view rather than a full copy whenever possible. That means that objects such as adata.obsm["spatial"] (which started out as a real NumPy array) can become an ArrayView in the sliced AnnData object.
To have an actual copy (with all arrays as raw NumPy),  calling:
filtered_data = data[data.obs[annotation].isin(values)].copy()
This makes a deep copy of all attributes (including .obsm["spatial"]) and ensures they remain as standard NumPy arrays rather than ArrayViews.
=> fix(select_values): adata.obsm remain numpy arrays

src/spac/visualization.py, tests/test_visualization/test_interactive_spatial_plot.py
Plotly does not have discrete colormap string for selection, the discrete color assignment is basing on the plotting data
Thus a continuous colormap with many colors in scale should give a good proximation to a discrete color map
More information about the plotly color map is in [Built-in Continuous Color Scales in Python](https://plotly.com/python/builtin-colorscales/).
=> perf: updating the default colormap for interactive spatial to rainbow

src/spac/visualization.py, tests/test_visualization/test_histogram.py
Updating the bin calculation to histogram in SPAC:
1. The automatic bin calculation for histogram in seaborn is slow for large row number and continuous data.
2. The Rice Rule is used for computation.
3. Implementation is through appending a "bins" arg into kwargs to minimize disturb of original function
=> feat: adding automated bin cal to histogram

src/spac/visualization.py, tests/test_visualization/test_boxplot_interactive.py
This PR removed the `interactive` parameter and adds a `figure_type` parameter. This still has the "interactive" and "png" options, but now has a "static" option which generates a static plotly figure. This can shave off >5 sec for the 10m dataset instead of converting the plotly figure to a PNG, and ideally should be used in Shiny over the png option.
* Add new `figure_type` parameter and remove `interactive`
* This new parameter allows the return plot to be plotly-interactive, plotly-static, and a png
* Transform static boxplot to plotly figure:
* When `figure_type` is static, boxplot is kept as plotly figure
* Disables (most) interactive features
* The "This plot was made using plotly" button cannot be disabled
* The cursor will still change when hovering over the plot, but it still …
=> Add Static Plotly Figure Return Type

src/spac/visualization.py
This pull request alters `src/spac/visualization.py` by updating the return dictionary in the `calculate_histogram` function
Corrections to return values:
* [`src/spac/visualization.py`](diffhunk://#diff-20e13a5111550712bb4f52c47c970e21f21d82299e3a2c5622eecc915abfd4bfL756-R758): Updated the return dictionary in the `calculate_histogram` function to return `hist_data` instead of `plot_data`.
=> Fix Histogram Return Value

src/spac/utils.py, tests/test_utils/test_get_defined_color_map.py
Summary:
This pull request allows the plotting of the spatial plot with multiple annotations.
Changes:
Add preparation of annotation data for labels on the colormap
Only this function failed to accept a list of strings, the rest of the function prepares the data correctly or accepts lists
Tests list acceptance
-Addition of unit test with set of annotations as list to show proper output
=> Spatial annos

src/spac/data_utils.py, tests/test_data_utils/test_select_values.py
This PR is handle the case when the "annotation" has numerical values (e.g., from phenograph), where select_values take a list of string.
=> fix(select_values): added support when observation are numerical

src/spac/transformations.py, tests/test_transformations/test_utag_clustering.py
add extensive comments for complex data set generation in UTAG tests.
Replaced one instance of a camel case with a snake case.
=> Add comments UTAG tests

src/spac/visualization.py, tests/test_visualization/test_hierarchical_heatmap.py
**Summary:**
Cell counts added to hierarchical heatmap so that users can see the number of cells in each cluster. A unit test was created to confirm the labels are added correctly.
**Changes:**
- visualization.py: Cell counts were retrieved and added to dendrogram/heatmap y-axis labels. 
- test_hierarchical_heatmap.py: A new unit test was defined where a simple anndata object with 1 cluster and known cell count was passed through the hierarchical heatmap function. The generated cell count labels were compared with expected cell count labels.
**Notes:**
Code was tested in code workbooks environment, and to avoid labels getting cut off, heatmap width was adjusted to provide extra margin. Please review/ suggest improvement.
=> Added Cell Counts to Dendrogram Labels

src/spac/data_utils.py
The original code still prints the list of row indices even when print_nan_locations is  False. It also prints the indices twice when it is True (message + summary), which clutters the log if tens of thousands of rows are missing, dumping all indices to the console can overwhelm CI log.
I have refactored the function code by commenting out the duplicated line that prints the index list inside the summary block, so keeps logs concise, preserves full detail when requested.
It affects only the console output—it does not change what the function returns. Therefore this unit test assertion remains valid.
=> fix(summarize_dataframe): remove duplicated missing index

src/spac/templates/template_utils.py
there is indeed a bug in NIDAP code. The intention is clearly to validate that both key and value are non-empty, but the current implementation has two issues:
Logic bug: not value checks if the list is empty, not if the string inside is empty. For "key:", we get value = [""], and not [""] is False, so it doesn't catch the empty value.
Duplicate assignment bug: The line parsed_dict[key] = value[0] appears twice - once inside the else block and again outside, which means duplicate keys would still get added to the dictionary.
=> feat(template_utils): add string_list_to_dictionary to template utils
